name: snsapp CI/CD

on:
  push:
    branches:
      - practice-werybalert

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTION_TOKEN }}
      #
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-7.3-bin.zip
          unzip -d /opt gradle-7.3-bin.zip
          export PATH=$PATH:/opt/gradle-7.3/bin
          gradle -v  
          
          pwd

      - name: Build Gradle
        run: |
          cd /home/runner/work/sns-notification-system/sns-notification-system/snsapp  
          pwd
          ls -al
          
          chmod +x ./gradlew
          ./gradlew build


      - name: Move App.jar to Current Directory
        run: |
          pwd
          ls -al
          mv snsapp/app-server/build/libs/app.jar ./
          
          pwd
          ls -al
      
      

      #
      - name: Connect to Server & Transfer Application
        uses: appleboy/scp-action@master  # scp 전송 확인

        with:
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: root
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_port: 22
          host: ${{ secrets.DEV_HOST }}
          username: root
          key: ${{ secrets.SSH_DEV_PRIVATE_KEY}}
          port: 22
          source: app.jar
          target: /var/app


          script: |
            echo "!!!!!success snsapp-deb-server!!!"
            pwd
            whoami
            ls -al
            ls /var/app



      - name: Run Application
        uses: appleboy/ssh-action@master

        with:
          proxy_host: ${{ secrets.PROXY_HOST }}
          proxy_username: root
          proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          proxy_port: 22

          host: ${{ secrets.DEV_HOST }}
          username: root
          key: ${{ secrets.SSH_DEV_PRIVATE_KEY}}
          port: 22

          script: |
            cd /var/app
            pwd
            ls -al
            
            
            ls -al
            ./app_run.sh
